### ISSUE TITLE
the affects of cumulativing aux loss steps

### ISSUE THREAD

**Issue by zjwang21** [IBM/ModuleFormer#5]
I didn't find the analysis of cumulative aux loss steps in the paper. I wonder cumulative more steps means doing load balancing in a larger batch, probably better performance?

Very interesting work.

**Comment by yikangshen** [comment]
Accumulating aux loss is not equivalent to a larger batch size, because the expert distribution is still computed within each step. But yes, computing the aux loss with a larger batch could potentially improve the load balancing and lead to better performance.

**Comment by zjwang21** [comment]
thanks for your reply

Yikang Shen ***@***.***> 于2023年11月17日周五 06:16写道：
